services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: trans-fat-api
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env.docker
    depends_on:
      - minio
      - postgres
      - redis
    command: sh -c "yarn prisma migrate deploy && yarn start"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BUCKETS: transfat-uploads
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9090"

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trans_fat
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
  minio-data:
